/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIDesktopBinding */

#ifndef _Included_JNIDesktopBinding
#define _Included_JNIDesktopBinding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIDesktopBinding
 * Method:    getAVG
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_JNIDesktopBinding_getAVG
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
